let governments = [
  { id: 1, name: "Cairo", price: 50 },
  { id: 2, name: "Giza", price: 45 },
  { id: 3, name: "Alexandria", price: 60 },
  { id: 4, name: "Dakahlia", price: 55 },
  { id: 5, name: "Red Sea", price: 70 },
  { id: 6, name: "Beheira", price: 50 },
  { id: 7, name: "Fayoum", price: 40 },
  { id: 8, name: "Gharbia", price: 45 },
  { id: 9, name: "Ismailia", price: 50 },
  { id: 10, name: "Monufia", price: 40 },
  { id: 11, name: "Minya", price: 65 },
  { id: 12, name: "Qalyubia", price: 45 },
  { id: 13, name: "New Valley", price: 80 },
  { id: 14, name: "Suez", price: 55 },
  { id: 15, name: "Aswan", price: 90 },
  { id: 16, name: "Assiut", price: 70 },
  { id: 17, name: "Beni Suef", price: 60 },
  { id: 18, name: "Port Said", price: 55 },
  { id: 19, name: "Damietta", price: 50 },
  { id: 20, name: "Sharqia", price: 50 },
  { id: 21, name: "South Sinai", price: 85 },
  { id: 22, name: "Kafr El Sheikh", price: 55 },
  { id: 23, name: "Matruh", price: 95 },
  { id: 24, name: "Luxor", price: 85 },
  { id: 25, name: "Qena", price: 75 },
  { id: 26, name: "North Sinai", price: 90 },
  { id: 27, name: "Sohag", price: 70 },
];

export default governments;
